server:
  port: 80

spring:
  main:
    allow-bean-definition-overriding: true

cloud:
  aws:
    region:
      static: us-east-1
    credentials:
      access-key: 12345
      secret-key: 12345
    endpoint: http://localhost:4566

sqs:
  contratacao: DEV_CONTRATACAO
  bemVindo: DEV_CONTRATACAO_BEM_VINDO
